{% set name = "eth-account" %}
{% set version = "0.5.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee62e121d977ca452f600043338af36f9349aa1f8409c5096d75df6576c79f1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - bitarray >=1.2.1,<3
    - eth-abi >=2.0.0b7,<3
    - eth-keyfile >=0.5.0,<0.6.0
    - eth-keys >=0.3.4,<0.4.0
    - eth-rlp >=0.1.2,<2
    - eth-utils >=1.3.0,<2
    - hexbytes >=0.1.0,<1
    - rlp >=1.0.0,<3

test:
  imports:
    - eth_account
    - eth_account._utils
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-account
  summary: 'eth-account: Sign Ethereum transactions and messages with local private keys'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
