{% set name = "eth-account" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54b0b7d661e73f4cd12d508c9baa5c9a6e8c194aa7bafc39277cd673683ae50e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - bitarray >=1.2.1,<1.3.0
    - eth-abi >=3.0.0,<4
    - eth-keyfile >=0.6.0,<0.7.0
    - eth-keys >=0.4.0,<0.5
    - eth-rlp >=0.3.0,<1
    - eth-utils >=2.0.0,<3
    - hexbytes >=0.1.0,<1

test:
  imports:
    - eth_account
    - eth_account._utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-account
  summary: 'eth-account: Sign Ethereum transactions and messages with local private keys'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
